AllCops:
  TargetRubyVersion: 3.0.2
  NewCops: enable
Metrics/LineLength:
  Max: 100
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/ModuleLength:
  Exclude:
    - "**/*test_*.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*test_*.rb"
Lint/BinaryOperatorWithIdenticalOperands:
  Exclude:
    - "**/*test_*.rb"
Lint/IdentityComparison:
  Exclude:
    - "**/*test_*.rb"
Layout/MultilineOperationIndentation:
  Exclude:
    - "**/*test_*.rb"
